아래 강의 노트는 [Python for data Analysis 책](https://github.com/wesm/pydata-book)4장을 기반으로 번역 및 편집하여 페이지 구성함  
<img src ="https://image.yes24.com/goods/73268296/800x0" width=5%>

 **무단 배포를 금지 합니다.** 

***

# 고급 배열 조작기법
## 배열 재형성
```reshape``` 를 이용해 새로운 모양을 나태는 튜플을 넘기기

In [1]:
import numpy as np
arr = np.arange(8)
print(arr)
arr= arr.reshape((4, 2))
print(arr)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


다차원 배열 또한 재형성 가능

In [2]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

reshpae에 넘기는 값중 하나가 -1 가능    
원본 데이터를 참조하여 적절한 값으로 추론

In [3]:
arr = np.arange(15)#0~14
arr=arr.reshape((3, 5, -1)) # 3 x 5 x1
arr

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]]])

In [4]:
arr.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

다차원 배열을 낮은 차원으로 **평탄화(flattening raveling)** 가능 

In [5]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [6]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
arr = np.arange(15).reshape((5, 3))
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##  배열 이어 붙이고 나누기

In [8]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # 2X3
arr2 = np.array([[7, 8, 9], [10, 11, 12]])  #2x3

In [9]:
np.concatenate([arr1, arr2], axis=0) # 4 x 3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
np.concatenate([arr1, arr2], axis=1) # 2 x 6

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [11]:
np.vstack((arr1, arr2)) #np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
np.hstack((arr1, arr2)) #np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

```split``` 매서드를 사용하면 하나의 배열을 축을 따라 여러개의 배열로 나눌 수 있음
여기에서 [2,3]은 split되는 인덱스를 의미 

In [13]:
arr = np.random.randn(5, 2)
print(arr)
first, second, third = np.split(arr, [1, 2])

[[-0.49057222  0.48928108]
 [-0.19249557 -0.21311584]
 [ 1.83917072 -0.50240216]
 [-0.22958529 -0.16704125]
 [ 0.70771715  0.09687626]]


In [14]:
first

array([[-0.49057222,  0.48928108]])

In [15]:
second

array([[-0.19249557, -0.21311584]])

In [16]:
third

array([[ 1.83917072, -0.50240216],
       [-0.22958529, -0.16704125],
       [ 0.70771715,  0.09687626]])

## 반복 엘리먼트

큰 배열을 만들기 위해 배열을 복사하거나 복제하는 함수로 ```repeat```와 ```tile```이 있다.    
```repeat```는 한 배열의 각 원소를 원하는 만큼 복제해서 큰 배열을 생성

In [1]:
arr = np.arange(3)  # 0 1 2 
print(arr)
arr.repeat(3) # 000 111 222 

[0 1 2]


array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [2]:
arr = np.random.randn(2, 2)
print(arr)
arr = arr.repeat(2, axis=0)
arr.repeat(2, axis=1)



[[ 1.11533109  0.55882597]
 [-0.05660742 -1.78747451]]


array([[ 1.11533109,  1.11533109,  0.55882597,  0.55882597],
       [ 1.11533109,  1.11533109,  0.55882597,  0.55882597],
       [-0.05660742, -0.05660742, -1.78747451, -1.78747451],
       [-0.05660742, -0.05660742, -1.78747451, -1.78747451]])

```tile```은  축을 따라 배열을 복사해서 쌓는 함수 <br>타일을 이어 붙이듯이 같은 내용의 배열을 이어 붙이기

In [4]:
import numpy as np
arr = np.random.randn(2, 2)
print(arr)
np.tile(arr, (2, 2))

[[0.04061595 0.13505418]
 [0.42147568 1.13623832]]


array([[0.04061595, 0.13505418, 0.04061595, 0.13505418],
       [0.42147568, 1.13623832, 0.42147568, 1.13623832],
       [0.04061595, 0.13505418, 0.04061595, 0.13505418],
       [0.42147568, 1.13623832, 0.42147568, 1.13623832]])

In [5]:
np.tile(arr,(2, 2))

array([[0.04061595, 0.13505418, 0.04061595, 0.13505418],
       [0.42147568, 1.13623832, 0.42147568, 1.13623832],
       [0.04061595, 0.13505418, 0.04061595, 0.13505418],
       [0.42147568, 1.13623832, 0.42147568, 1.13623832]])

## 브로드캐스팅 <br>

다른 모양의 배열 간의 산술연산을 어떻게 수행 하는 지 설명   
**브로드 캐스팅 규칙:**   
이어지는 각 차원에 대해 축의 길이가 일치 하거나 둘중 하나가 길이가 1이라면 두 배열을 브로드캐스팅 호환이다.   
브로드캐트닝은 누락된 혹은 길이가 1인 차원에 대해 수행   
<img src="https://i.pinimg.com/736x/95/db/fa/95dbfa11a4f650c55823da7111f1c2ef.jpg" width=50%> 

In [6]:
arr1 = np.around(np.random.randn(4, 3)*10)
print(arr1)
arr2 =np.around(np.random.randn(3,)*10) 
print("arr2\n\n",arr2)
arr1 + arr2

[[ 30. -12.  22.]
 [  7.  -6.  18.]
 [  8. -17.   1.]
 [ -4.   5.   7.]]
arr2

 [5. 7. 5.]


array([[ 35.,  -5.,  27.],
       [ 12.,   1.,  23.],
       [ 13., -10.,   6.],
       [  1.,  12.,  12.]])

아래 예제는 4x3행렬을 만들고 각 행에 대한 평균값을 뺀다고 가정 

In [7]:
arr1 = np.around(np.random.randn(4, 3)*10)
print(arr1)
row_mean = arr1.mean(1)
print(row_mean)
print(row_mean.shape)
ar

SyntaxError: invalid syntax (<ipython-input-7-b9dc4fdc8d2e>, line 7)

<img src="https://i.pinimg.com/736x/95/db/fa/95dbfa11a4f650c55823da7111f1c2ef.jpg" width=50%>   
아래는 3차원 배열의 0번축에 대해 2차원 배열의 값을 더하는 과정
<img src="https://t1.daumcdn.net/cfile/tistory/992C603359DA68C815" width=50%>

다차원의 배열에서 브로드캐스팅은 규칙을 잘 따라야 계산 <br><br>
아래는 차원이 맞지 않을 경우에 대한 에러

In [8]:
dim_main_sub = arr1 - row_mean.reshape(4,1) #아래는 차원이 맞은 브로드캐스팅
dim_main_sub
dim_main_sub = arr1 - row_mean #아래는 차원이 맞지 않을 경우에 대한 에러

NameError: name 'row_mean' is not defined

<img src="http://www.astroml.org/_images/fig_broadcast_visual_1.png">

In [9]:
np.arange(3)+np.arange(3)

array([0, 2, 4])