### list_enumerate

In [16]:
some_list = ['foo', 'bar', 'baz']

mapping = {}
for i, v in enumerate(some_list):
    # start를 사용하여 시작 인덱스 정할 수 있음 for i, v in enumerate(some_list, start = 5):
    mapping[v] = i
    print("i: ", i, "\nv: ", v)
    print(mapping)
    print("some_list: ", some_list)           # enumerate() 함수는 기본적으로 인덱스와 원소로 이루어진 터플(tuple)을 만들어줍니다.
mapping

i:  0 
v:  foo
{'foo': 0}
some_list:  ['foo', 'bar', 'baz']
i:  1 
v:  bar
{'foo': 0, 'bar': 1}
some_list:  ['foo', 'bar', 'baz']
i:  2 
v:  baz
{'foo': 0, 'bar': 1, 'baz': 2}
some_list:  ['foo', 'bar', 'baz']


{'foo': 0, 'bar': 1, 'baz': 2}

### list [ sorted, reversed ]

In [24]:
sortlist_num =sorted([7, 1, 2, 6, 0, 3, 2])
print(sortlist_num)

sortlist_eng = sorted('gorse race')
print(sortlist_eng)

reversed_num= reversed(sortlist_num)
print("sortlist_num 리버스: ", reversed_num)

print("reversed_num 타입: ", type(reversed_num))

print("sortlist_num 리버스: ", list(reversed_num))            # 리스트로 꼭 묶어주기

[0, 1, 2, 2, 3, 6, 7]
[' ', 'a', 'c', 'e', 'e', 'g', 'o', 'r', 'r', 's']
sortlist_num 리버스:  <list_reverseiterator object at 0x7fe499e5d4c0>
reversed_num 타입:  <class 'list_reverseiterator'>
sortlist_num 리버스:  [7, 6, 3, 2, 2, 1, 0]


### list [ zip ]

In [28]:
zipped_list = zip(sortlist_num, sortlist_eng)

print("zipped_list 타입: ", type(zipped_list))

print(zipped_list)        # 리스트로 꼭 묶어주기

print(list(zipped_list))

zipped_list 타입:  <class 'zip'>
[(0, ' '), (1, 'a'), (2, 'c'), (2, 'e'), (3, 'e'), (6, 'g'), (7, 'o')]


### tuples(튜플)는 append, remove, insert, reverse, sort 지원 x

In [15]:
tup = 4, 5, 6 
print("tup 타입: ", type(tup), "          tup: ",tup)

tup = tuple([4, 0, 2])
print(tup)
tup = tuple('string')

print("tuple('string'), 이렇게 넣으면 문자열이 쪼개져서 저장이됨" , tup)

tup = tuple(['foo', [1, 2], True])

# # tup[2] = False
# print(tup[2])

print("\ntup: ", tup)

tup[1].append(90)                 # tuple 속 리스트 [1,2] 뒤에 3을 추가한다/
print("\ntup: ", tup)



tup 타입:  <class 'tuple'>           tup:  (4, 5, 6)
(4, 0, 2)
tuple('string'), 이렇게 넣으면 문자열이 쪼개져서 저장이됨 ('s', 't', 'r', 'i', 'n', 'g')

tup:  ('foo', [1, 2], True)

tup:  ('foo', [1, 2, 90], True)


### Unpacking tuples 튜플 쪼개기

In [20]:
tup = (4, 5, 6)
print("쪼개기 전 튜플: ", tup)

a, b, c = tup # 튜플 쪼개기

print("쪼깨고 b값 갖고 오기, b: ", b)

쪼개기 전 튜플:  (4, 5, 6)
쪼깨고 b값 갖고 오기, b:  5


### temp 이용, temp = a a = b b = temp

In [21]:
a, b = 1,5 

In [27]:
print("temp 활용 전")
print("\n a: ", a)
print("\n b: ", b)

temp 활용 전

 a:  5

 b:  1


In [30]:
b, a = a, b
print("\n temp 활용 후 ", a)
print("\n temp 활용 후 ", b)


 temp 활용 후  1

 temp 활용 후  5


### 리스트 속 튜플 속 값들 추출하기

In [37]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
print(seq)

for a, b, c in seq:
    print('a={0}, b={1}, c={2}'.format(a, b, c))
    


[(1, 2, 3), (4, 5, 6), (7, 8, 9)]
a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


In [61]:
values = 1, 2, 3, 4, 5

a, b, *rest = values

print("values: ", values)
print("a: ", a)
print("b: ", b)
print("*rest: ", *rest)
print("rest: ", rest)
a, b, *_ = values
print(*_)
                                                            # 포인터라고 생각하면 편함

values:  (1, 2, 3, 4, 5)
a:  1
b:  2
*rest:  3 4 5
rest:  [3, 4, 5]
3 4 5


### 튜플 메소드

In [64]:
a = 1, 2, 2, 2, 3, 4, 2
a.count(2)

4

### 딕셔너리
#### 딕셔너리 안에서 키 값이 있는지 없는 지 확인을 위해서 in 과 not in 연산자를 이용한다.
#### 딕셔너리에서 dictionary[key]와 같은 포맷으로 딕셔너리내의 key 값을 가지고 있는 값들을 나타낼 수 있음
#### 만약 딕셔너리 안에서 key값이 없다면 keyerror 에러 발생 
#### 딕셔너리 자체는 변경가능 한 객체이다. 키와 값의 쌍으로 추가하기 위해서 dictionary[key] = value 
#### 만약 키 값이 이미 존재하고 있따면, 그 값을 바꾼다. 

In [85]:
empty_dict = {}
d1 = {'a' : 'some value', 'b' : [1, 2, 3, 4]}
d1

{'a': 'some value', 'b': [1, 2, 3, 4]}

In [86]:
d1[7] = 'an integer'           # 이렇게 값 추가 가능 찬영이형 코드 참조
print(d1)
print(d1['b'])

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}
[1, 2, 3, 4]


In [87]:
'b' in d1

True

In [88]:
print(d1)
del d1['b']
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}


{'a': 'some value', 7: 'an integer'}

In [89]:
ret = d1.pop('a')
ret

'some value'

In [90]:
list(d1.keys())

[7]

In [91]:
list(d1.values())

['an integer']

In [96]:
d1.update({'d': 'foo', 'c':12})

In [97]:
d1

{7: 'an integer', 'd': 'foo', 'c': 12}

In [98]:
a = dict(zip(range(5), reversed(range(5))))            # 0, 1, 2, 3, 4     :     4, 3, 2, 1, 0   키와 밸류값으로 저장
a

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

### Set 수학의 세트와 유사, 모든 원소값은 유일, 정렬x, 서로 다른타입 원소 초기화 가능

In [101]:
s1 = set([1, 4, 2, 3, 2, 3])
s1

{1, 2, 3, 4}

### 여기에서 argument는 리스트 스트링 튜풀 가능
### 만약 argument가 문자열이라면, 하나씩떨어트려놈 문자열을 리스트로 하나씩 떨어트려 만듦
#### argument 안에 중복되는 원소값이 있다면 하나만 보여줌

### intersecion of two sets: 두 셋트에서 모두 공통으로 갖고 있는 원소 값을 찾아냄
- 두가지 방법: 
- intersection 함수 이용, ex) Format: set1.intersection(set2)
- &연산자 이용, Format: set1 & set2
- 결과는 모두 새로운 Set로 넘겨줌

In [119]:
# &연산자 이용, Format: set1 & set2

s1 = set(range(10))
s2 = set(range(1, 5))
print("S1: ", s1)
print("S2: ", s2)
print("s1 & s2: ", s1 & s2) 

# intersection 함수 이용

print("s1.intersection(s2): ", s1.intersection(s2))
print("s2.intersection(s1): ", s2.intersection(s1))

S1:  {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
S2:  {1, 2, 3, 4}
s1 & s2:  {1, 2, 3, 4}
s1.intersection(s2):  {1, 2, 3, 4}
s2.intersection(s1):  {1, 2, 3, 4}


### 세트의 차집합
두가지 밥법, difference함수 이용 or s1-s2

In [123]:
print("s1-s2: ", s1-s2)

print("s1.difference(s2): ", s1.difference(s2))

s1-s2:  {0, 5, 6, 7, 8, 9}
s1.difference(s2):  {0, 5, 6, 7, 8, 9}


### 세트에서 합집합에서 교집합을 뺀 모든 원소값
- symmetric_difference 사용
- ^연산자 사용

In [126]:
print("s1.symmetric_difference(s2): ", s1.symmetric_difference(s2))
print("s2.symmetric_difference(s1): ", s2.symmetric_difference(s1))

s1.symmetric_difference(s2):  {0, 5, 6, 7, 8, 9}
s2.symmetric_difference(s1):  {0, 5, 6, 7, 8, 9}


.copy 사용하기, issubset() 사용하기
a.issubset(b) / a가 b안에 포함되어있느가? boolean return

In [133]:
s3 = s1.copy()
s1.issubset(s2)
s2.issubset(s1)

True

### ndarrays 생성하기

배열을 생성하는 가장 쉬운 방법은 ```array``` 함수 이용     
예: 파이썬의 리스트는 변환하기 좋은 예

In [135]:
import numpy as np

data1 = [6, 8.2, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 8.2, 0. , 1. ])

In [136]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2.ndim

2

In [138]:
arr2.ndim

2

In [139]:
arr2.shape

(2, 4)

In [140]:
arr1.dtype

dtype('float64')

In [141]:
arr2.dtype

dtype('int64')

### numpy 아래 같은 뜻임

arr2d[0][2] , arr2d[0,2]

In [143]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],[10,11,12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [145]:
old_values = arr3d[0]#.copy()
arr3d[0]=42
##################################        2차원 배열 2개를 하나의 배열 안에다가 넣음, 그 중 첫번째 2차원 배열을 42로 복사
arr3d[0]=old_values
arr3d
#old_values

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [146]:
arr3d[1, 0,2]                   # 2차원 배열 2개를 하나의 배열 안에다가 넣었는데, 그 중 2번째 2차원 배열의 세로0, 가로2번째를 갖고옴

9